# Generated by Django 3.2 on 2021-05-02 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('hours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
