# Generated by Django 3.0.7 on 2021-05-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0002_auto_20210502_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
